version: 2

default_steps: &steps
  steps:
    - checkout
    - run:
        name: Install Python dependencies
        command: pip3 install pytest-cov pytest-mpl mock fast-histogram
    - run:
        name: Run tests
        command: MPLBACKEND=Agg pytest mpl_scatter_density --mpl -p no:warnings --cov mpl_scatter_density

jobs:

  image-tests-mpl202:
    docker:
      - image: astropy/image-tests-py35-mpl202:1.4
    <<: *steps

  image-tests-mpl212:
    docker:
      - image: astropy/image-tests-py35-mpl212:1.4
    <<: *steps

  image-tests-mpl222:
    docker:
      - image: astropy/image-tests-py35-mpl222:1.4
    <<: *steps

  image-tests-mpl300:
    docker:
      - image: astropy/image-tests-py35-mpl300:1.4
    <<: *steps

  image-tests-mpldev:
    docker:
      - image: astropy/image-tests-py36-base:1.1
    steps:
      - checkout
      - run:
          name: Install apt dependencies
          command: apt-get install -y libfreetype6-dev libpng12-dev pkg-config python3-tk
      - run:
          name: Install Python dependencies, including developer version of Matplotlib
          command: pip3 install pytest-cov pytest-mpl mock fast-histogram numpy git+https://github.com/matplotlib/matplotlib.git
      - run:
          name: Run tests
          command: pytest mpl_scatter_density --mpl -p no:warnings --cov mpl_scatter_density


workflows:
  version: 2
  tests_and_docs:
    jobs:
      - image-tests-mpl202
      - image-tests-mpl212
      - image-tests-mpl222
      - image-tests-mpl300
      - image-tests-mpldev
